require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - bin/**/*
    - coverage/**/*
    - db/schema.rb
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
  EnabledByDefault: true

### Rails

Rails/FilePath:
  EnforcedStyle: arguments

Rails/SkipsModelValidations:
  Enabled: false

Rails/SchemaComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

### Bundler

Bundler/OrderedGems:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

### Metrics

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 140

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 120

### Style

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/QuotedSymbols:
  EnforcedStyle: single_quotes

Style/RequireOrder:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MultilineIfModifier:
  Enabled: false

### Layout

Layout:
  Enabled: false

Layout/LineLength:
  Max: 190
  AllowedPatterns: ['\A#'] # Allow long comments

# Lint

Lint/ConstantResolution:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

# Performance

Performance/ChainArrayAllocation:
  Enabled: false

Performance/OpenStruct:
  Enabled: false
