require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - coverage/**/*
    - db/schema.rb
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
  EnabledByDefault: true

### Rails

Rails/FilePath:
  EnforcedStyle: arguments

Rails/SkipsModelValidations:
  Enabled: false

### Bundler

Bundler/OrderedGems:
  Enabled: false

### Metrics

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 140

Metrics/MethodLength:
  Max: 30

### Style

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

### Layout

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/LineLength:
  Max: 190
  IgnoredPatterns: ['\A#'] # Allow long comments

# Lint

Lint/ConstantResolution:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

# Performance

Performance/ChainArrayAllocation:
  Enabled: false

Performance/OpenStruct:
  Enabled: false
